### ISSUE TITLE
Need more seed nodes

### ISSUE THREAD

**Issue by Ronsor** [tinyrcoin/tkwallet#1]
We need more seed nodes and peers for the network. If you would like to be included, follow these steps:

1. Make sure port 12990 is forwarded on your router (the network p2p port)
2. Make sure you leave your computer on ALL the time (excluding updates, or other necessary restarts)
3. Reply with your IP address

Thank you for helping RCoin!

**Comment by mohaxars** [comment]
hey from pool.ddclub.org i would love to run a node

**Comment by Ronsor** [comment]
Ok. Just follow the instructions in the first post. @mohaxars

**Comment by Ronsor** [comment]
We have enough seed nodes for now.
